name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.27
homepage: https://github.com/ThinkSimple/flutter_simple_shopify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  pedantic: ^1.11.1
