name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.27
homepage: https://github.com/ThinkSimple/flutter_simple_shopify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  freezed_annotation: ^2.2.0
  json_serializable: ^6.1.4
  shared_preferences: ^2.0.13
  intl: ^0.18.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^2.2.0
  pedantic: ^1.11.1
